---
title: "pixar"
format: html
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
```

# The Data

Let's explore a data set about the ratings of pixar films Pixar films; the data here is from the [TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-03-11) repo and the original data is from [Wikipedia](https://en.wikipedia.org/wiki/List_of_Pixar_films).

```{r}
#| message: false
#| warning: false
pixar_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-03-11/public_response.csv')
```

# Let's plot it!

```{r}
#| message: false
#| warning: false

pixar_ratings_long <- pixar_ratings |>
  pivot_longer(
    cols = c(rotten_tomatoes, metacritic, critics_choice),
    names_to = "rating_source",
    values_to = "score"
  )|>
  filter(!is.na(score)) 

ggplot(pixar_ratings_long, aes(x = film, y = score, color = rating_source)) +
  geom_point(size = 3) +
  geom_line(aes(group = rating_source)) +
  labs(
    title = "Pixar Movie Ratings",
    x = "Film",
    y = "Score",
    color = "Rating Source"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
  
```

# References
“List of Pixar Films.” Wikipedia, Wikimedia Foundation, 4 Dec. 2025, [en.wikipedia.org/wiki/List_of_Pixar_films](en.wikipedia.org/wiki/List_of_Pixar_films). 
